FROM mcr.microsoft.com/vscode/devcontainers/miniconda:3

# Expose port 8000
EXPOSE 8000

# COPY ./environment.yml /workspaces/MedApp-Dev-AI/environment_1.yml\

# RUN conda env create -f /workspaces/MedApp-Dev-AI/environment.yml
 